apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-loki-operator
spec:
  size: 1x.demo
  managementState: Managed
  limits:
    global:
      retention:
        days: 7
  storage:
    schemas:
      - effectiveDate: "2024-10-01"
        version: v13
    secret:
      name: loki-minio-credentials
      type: s3
  storageClassName: gp3-csi
  tenants:
    mode: openshift-logging
