kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1
metadata:
  name: default
spec:
  components:
    kserve:
      managementState: Managed
      defaultDeploymentMode: Serverless
      serving:
        managementState: Managed
        name: knative-serving
