apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - dspa.yaml

patches:
  - target:
      kind: DataSciencePipelinesApplication
    path: patch-dspa-for-fast.yaml
