apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-training

resources:
  - ../../base
  - dspa.yaml

patches:
  - target:
      kind: DataSciencePipelinesApplication
    path: patch-dspa-for-2.16-aws-gpu.yaml
